### ISSUE TITLE
Repository does not have a CODEOWNERS file

### ISSUE THREAD

**Issue by JianLoong** [JianLoong/FIT5032-S2-2018#24]
The current repository does not have a CODEOWNERS file.

Please refer [here](https://blog.github.com/2017-07-06-introducing-code-owners/) to see what the file is all about. 

Since I am the owner of this repository, I would like to be notified, when a pull request is made.

**Comment by ooxaam** [comment]
@JianLoong Hi, I have made changes. kindly let me know if they are working perfect for you :+1: 

Have a good day :)

**Comment by JianLoong** [comment]
@ooxaam Good work. 😄 😆
